const Words = {
	GREETING: '님, 안녕하세요',
	ID: '아이디',
	PASSWORD: '비밀번호',
	EMAIL: '이메일',
	LOGIN: '로그인',
	LOGOUT: '로그아웃',
	SIGNUP: '회원가입',
	TITLE: '제목',
	CATEGORY: '카테고리',
	FILE: '파일',
	ORIGIN: '원본',
	DESCRIPTION: '설명',
	KEYWORD: '키워드',
	SUBJECT: '주제',
	GO: ' 하러가기',
	ADD: '작성',
	SAVE: '저장',
	DELETE: '삭제',
	SEARCH: '검색',
	SELECT: '선택',
	CANCEL: '취소',
	ALL_CHECK: '전체선택',
	CHANGE_FILE: '파일 변경',
	UPDATE: '수정',
	PROJECT_NAME: 'S-STT',
	GOOGLE: 'Google',
	NAVER: 'Naver',
	KAKAO: 'Kakao',
	ASK_MEMBER: '아직 회원이 아니신가요? ',
	ASK_DELETE_POST: '해당 게시글을 정말로 삭제하시겠습니까?',
	ASK_DELETE_POSTS: '선택한 게시글들을 정말로 삭제하시겠습니까?',
	ASK_ADD_CANCEL: '작성중인 게시글은 저장되지 않습니다.\n정말로 게시글 작성을 취소하시겠습니까?',
	ASK_UPDATE_CANCEL: '수정중인 게시글은 저장되지 않습니다.\n정말로 게시글 수정을 취소하시겠습니까?',
	DUPLICATE_KEYWORDS: '은/는 중복되는 키워드입니다. 다른 키워드를 입력해주세요',
	ENTER_ID: '아이디를 입력해주세요',
	ENTER_PASSWORD: '비밀번호를 입력해주세요',
	ENTER_EMAIL: '이메일을 입력해주세요',
	ENTER_TITLE: '제목을 입력해주세요',
	ENTER_DESCRIPTION: '설명을 입력해주세요 (최대 100자)',
	ENTER_KEYWORD: '키워드를 입력해주세요',
	ENTER_SUBJECT_TITLE: '주제의 제목을 입력해주세요',
	ENTER_SUBJECT_CONTENT: '주제에 맞는 본문의 내용을 입력해주세요',
	ID_CONDITION: '5~20자의 알파벳과 숫자만을 이용하여 입력해주세요',
	PASSWORD_CONDITION: '비밀번호는 8자 이상 입력해주세요',
	EMAIL_CONDITION: `이메일은 '아이디@주소' 형태로 입력해주세요`,
	NO_POST: '작성된 게시글이 없습니다.',
	WRITE_POST: '작성버튼을 눌러 새 게시글을 작성해주세요😊',
	SELECT_POST: '삭제할 게시글을 선택해주세요',
	SELECT_FILE: '파일을 선택해주세요',
	LIMIT_TITLE_LENGTH: '제목은 20자 이내로 입력해주세요',
	LIMIT_DESCRIPTION_LENGTH: '설명은 100자 이내로 입력해주세요',
	LIMIT_KEYWORDS_NUMBER: '키워드는 30개 이내로 입력해주세요',
	MAX_DESCRIPTION_LENGTH: '100자',
	MAX_TITLE_LENGTH: ' (최대 20자)',
};

export default Words;
